### ISSUE TITLE
One master final review issue

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-data-handbook#476]
One final review issue to rule them all. Feel free to add more things to this issue, but please follow this organzition:

* Each thing should start with a checkbox `- [ ]` so we can track what has been done
* Each comment box is a topic, add things by editing the appropriate box (if you can) instead of create a new comment box. If you cannot edit, just create a new comment box and I will fix

**Comment by kbjarkefur** [comment]
## Consistent writing 

- [ ] Write **dataset** not **data set** (old #413)
- [ ] Write **original data** not **primary data** or **raw data** when referring to the dataset the project acquires. If talking about data collection specifically you can still say _primary data_ and _raw data_ (old #387)
- [ ] Write **analysis data** not **constructed data** (old #475)
- [ ] Write **confidential data** not **personally-identified data** (or **PII data**) when talking about what data is sensitive and needs to be encrypted. _PII data_ is one reason for data being confidential, and in that specific case we can say _PII data_ (old #454)

**Comment by kbjarkefur** [comment]
## Book structure

- [ ] review the sections and paragraphs follow this rules (old #423)
    * each paragraph with a statement followed by supporting evidence or examples
    * each subsection with a structure
    * make sure to draw the distinction between what others have done and what our contribution has been.
- [ ] make sure we call sub-section for _sub-section_ and not _section_ (old #455)

**Comment by kbjarkefur** [comment]
## Chapter diagrams

- [ ] make sure font size is good when diagrams are in book (old #474)

**Comment by kbjarkefur** [comment]
## Links in book

- [ ] Check that URLs that only point to allowed resources. (old #428 ) Everything else should be moved to Wiki, defined in sidenote, or cited as an academic reference. Allowed URLs are: 
    - DIME wiki
    - Any worldbank.org link (including blogs, docs, etc.)
    - Any WB/DIME GitHub repository
    - Links to _top-level domain_ of specific sites or services referenced

**Comment by kbjarkefur** [comment]
## Make sure concepts are explained

Concepts used in each chapter:

### Chapter Intro and 1
- [ ] Reproducibility
- [ ] Transparency
- [ ] Credibility
- [ ] Computational reproducibility
- [ ] Master script
- [ ] Pre-registration
- [ ] Pre-analysis plan
- [ ] Registered reports
- [ ] File-drawer problem
- [ ] PII
- [ ] Data ownership
- [ ] "Confidential data"
- [ ] IRB
- [ ] Encryption
- [ ] Human subjects
- [ ] De-identification
- [ ] Anonymization
- [ ] Risk of disclosure

**Comment by bbdaniels** [comment]
# Make sure all concepts are indexed correctly

**Comment by luizaandrade** [comment]
- [ ] Check usage of "ID", "identifier" and "identifying variable" across the book.

**Comment by bbdaniels** [comment]
Indexing: 

It is \index{} and \sidenote{} in conjunction, and sometimes new line in text editor. To solve this try the following:

Since \index{} does not appear in the text, see if it can be moved so it is one word, or even just a full stop removed from \sidenote{}. Obviously do not move it too far as we do not want the page references on the index page to be imprecise.
\index{} should not be on a new row by itself.
Make sure that some word or character follows on the same line as \sidenote{}, as in the closing bracket } in \sidenote{} is not the last character on that line in the text editor.
